2024-12-07 00:08:00,775 - __main__ - INFO - Starting enhanced model training process...
2024-12-07 00:08:06,031 - __main__ - ERROR - Error in load_data: An error occurred while calling o36.collectToPython.
: org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.spark.sql.delta.catalog.DeltaCatalog.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.catalogPluginClassNotFoundForCatalogError(QueryExecutionErrors.scala:1925)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:70)
	at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:67)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:86)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$1(CatalogManager.scala:86)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.connector.catalog.CatalogManager.v2SessionCatalog(CatalogManager.scala:85)
	at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:51)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:122)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentNamespace(CatalogManager.scala:93)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:110)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:107)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.$anonfun$apply$1(Optimizer.scala:293)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:293)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:275)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:152)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:148)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:162)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:179)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:252)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:117)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.delta.catalog.DeltaCatalog
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
	... 62 more

2024-12-07 00:08:06,092 - __main__ - ERROR - Error in model training: An error occurred while calling o36.collectToPython.
: org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.spark.sql.delta.catalog.DeltaCatalog.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.catalogPluginClassNotFoundForCatalogError(QueryExecutionErrors.scala:1925)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:70)
	at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:67)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:86)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$1(CatalogManager.scala:86)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.connector.catalog.CatalogManager.v2SessionCatalog(CatalogManager.scala:85)
	at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:51)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:122)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentNamespace(CatalogManager.scala:93)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:110)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:107)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.$anonfun$apply$1(Optimizer.scala:293)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:293)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:275)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:152)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:148)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:162)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:179)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:252)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:117)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.delta.catalog.DeltaCatalog
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
	... 62 more

2024-12-07 00:08:06,092 - __main__ - ERROR - Error in main: An error occurred while calling o36.collectToPython.
: org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.spark.sql.delta.catalog.DeltaCatalog.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.catalogPluginClassNotFoundForCatalogError(QueryExecutionErrors.scala:1925)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:70)
	at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:67)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:86)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$1(CatalogManager.scala:86)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.connector.catalog.CatalogManager.v2SessionCatalog(CatalogManager.scala:85)
	at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:51)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:122)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentNamespace(CatalogManager.scala:93)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:110)
	at org.apache.spark.sql.catalyst.optimizer.ReplaceCurrentLike.apply(finishAnalysis.scala:107)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.$anonfun$apply$1(Optimizer.scala:293)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:293)
	at org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis$.apply(Optimizer.scala:275)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:152)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:148)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:162)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:179)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:252)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:117)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.delta.catalog.DeltaCatalog
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
	... 62 more

2024-12-07 00:08:06,096 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:04,204 - __main__ - INFO - Starting enhanced model training process...
2024-12-07 00:16:11,566 - __main__ - INFO - Successfully loaded tables:
2024-12-07 00:16:11,567 - __main__ - INFO - Revenue: (25, 6)
2024-12-07 00:16:11,567 - __main__ - INFO - Discount: (25, 7)
2024-12-07 00:16:11,567 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-07 00:16:11,567 - __main__ - INFO - Reviews: (25, 7)
2024-12-07 00:16:11,568 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-07 00:16:11,579 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-07 00:16:11,579 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-07 00:16:11,832 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-07 00:16:11,833 - __main__ - INFO - Number of numeric features: 23
2024-12-07 00:16:11,833 - __main__ - INFO - Number of categorical features: 3
2024-12-07 00:16:11,837 - __main__ - INFO - Training stacked model...
2024-12-07 00:16:11,872 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,883 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,888 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,894 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,900 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,905 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,913 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,921 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,932 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,942 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,951 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,964 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,979 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:11,998 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:12,067 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:12,108 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:12,119 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:12,744 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-07 00:16:12,746 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:12,746 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-07 00:16:12,749 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:14,496 - __main__ - INFO - Model Performance:
2024-12-07 00:16:14,496 - __main__ - INFO - R² score: 0.9832
2024-12-07 00:16:14,496 - __main__ - INFO - MSE: 5020.8544
2024-12-07 00:16:14,496 - __main__ - INFO - RMSE: 70.8580
2024-12-07 00:16:14,497 - __main__ - INFO - MAE: 60.7211
2024-12-07 00:16:14,497 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-07 00:16:14,498 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-07 00:16:14,498 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-07 00:16:14,548 - __main__ - INFO - Model saved to /home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-07 00:16:14,833 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:16:59,031 - __main__ - INFO - Starting enhanced model training process...
2024-12-07 00:17:07,819 - __main__ - INFO - Successfully loaded tables:
2024-12-07 00:17:07,820 - __main__ - INFO - Revenue: (25, 6)
2024-12-07 00:17:07,820 - __main__ - INFO - Discount: (25, 7)
2024-12-07 00:17:07,820 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-07 00:17:07,820 - __main__ - INFO - Reviews: (25, 7)
2024-12-07 00:17:07,820 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-07 00:17:07,824 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-07 00:17:07,824 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-07 00:17:08,131 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-07 00:17:08,131 - __main__ - INFO - Number of numeric features: 23
2024-12-07 00:17:08,131 - __main__ - INFO - Number of categorical features: 3
2024-12-07 00:17:08,133 - __main__ - INFO - Training stacked model...
2024-12-07 00:17:08,161 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,172 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,177 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,182 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,189 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,195 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,201 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,208 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,214 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,220 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,229 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,237 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,246 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,256 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,283 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,282 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,311 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,777 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-07 00:17:08,779 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:08,779 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-07 00:17:08,780 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-07 00:17:10,507 - __main__ - INFO - Model Performance:
2024-12-07 00:17:10,508 - __main__ - INFO - R² score: 0.9832
2024-12-07 00:17:10,508 - __main__ - INFO - MSE: 5020.8544
2024-12-07 00:17:10,508 - __main__ - INFO - RMSE: 70.8580
2024-12-07 00:17:10,508 - __main__ - INFO - MAE: 60.7211
2024-12-07 00:17:10,509 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-07 00:17:10,510 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-07 00:17:10,510 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-07 00:17:10,556 - __main__ - INFO - Model saved to /home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-07 00:17:10,848 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:04:18,457 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 01:04:21,957 - __main__ - WARNING - Error reading as Delta format: [PATH_NOT_FOUND] Path does not exist: file:/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/src/data/gold/revenue_per_category_parquet.
2024-12-08 01:04:21,957 - __main__ - INFO - Trying to read as parquet format...
2024-12-08 01:04:21,964 - __main__ - ERROR - Error in load_data: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:04:22,448 - __main__ - ERROR - Error in model training: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:04:22,448 - __main__ - ERROR - Error in main: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:04:22,452 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:07:12,497 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 01:07:19,532 - __main__ - WARNING - Error reading as Delta format: [PATH_NOT_FOUND] Path does not exist: file:/home/zaki/kuliah/Bigdata/data-lakehouse-fp-big-data/src/data/gold/revenue_per_category_parquet.
2024-12-08 01:07:19,533 - __main__ - INFO - Trying to read as parquet format...
2024-12-08 01:07:19,539 - __main__ - ERROR - Error in load_data: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:07:19,591 - __main__ - ERROR - Error in model training: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:07:19,592 - __main__ - ERROR - Error in main: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
2024-12-08 01:07:19,596 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:36,219 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 01:09:42,717 - __main__ - INFO - Successfully loaded tables:
2024-12-08 01:09:42,718 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 01:09:42,718 - __main__ - INFO - Discount: (25, 7)
2024-12-08 01:09:42,718 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 01:09:42,718 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 01:09:42,718 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 01:09:42,723 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 01:09:42,723 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 01:09:42,814 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 01:09:42,814 - __main__ - INFO - Number of numeric features: 23
2024-12-08 01:09:42,814 - __main__ - INFO - Number of categorical features: 3
2024-12-08 01:09:42,816 - __main__ - INFO - Training stacked model...
2024-12-08 01:09:42,846 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,862 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,868 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,879 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,890 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,897 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,920 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,934 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,947 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,947 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 01:09:42,961 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:42,961 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 01:09:42,992 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:43,031 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:43,047 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:44,021 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 01:09:44,021 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:44,022 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 01:09:44,023 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:09:45,840 - __main__ - INFO - Model Performance:
2024-12-08 01:09:45,840 - __main__ - INFO - R² score: 0.9832
2024-12-08 01:09:45,840 - __main__ - INFO - MSE: 5020.8544
2024-12-08 01:09:45,840 - __main__ - INFO - RMSE: 70.8580
2024-12-08 01:09:45,840 - __main__ - INFO - MAE: 60.7211
2024-12-08 01:09:45,841 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 01:09:45,842 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 01:09:45,842 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 01:09:45,914 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 01:09:46,155 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:11,225 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 01:14:17,713 - __main__ - INFO - Successfully loaded tables:
2024-12-08 01:14:17,713 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 01:14:17,713 - __main__ - INFO - Discount: (25, 7)
2024-12-08 01:14:17,713 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 01:14:17,713 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 01:14:17,713 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 01:14:17,718 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 01:14:17,718 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 01:14:18,053 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 01:14:18,053 - __main__ - INFO - Number of numeric features: 23
2024-12-08 01:14:18,053 - __main__ - INFO - Number of categorical features: 3
2024-12-08 01:14:18,057 - __main__ - INFO - Training stacked model...
2024-12-08 01:14:18,117 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,121 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,124 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,128 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,133 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,138 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,145 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,150 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,171 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:18,181 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:19,115 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 01:14:19,116 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:19,116 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 01:14:19,118 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 01:14:20,544 - __main__ - INFO - Model Performance:
2024-12-08 01:14:20,545 - __main__ - INFO - R² score: 0.9832
2024-12-08 01:14:20,545 - __main__ - INFO - MSE: 5020.8544
2024-12-08 01:14:20,545 - __main__ - INFO - RMSE: 70.8580
2024-12-08 01:14:20,545 - __main__ - INFO - MAE: 60.7211
2024-12-08 01:14:20,545 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 01:14:20,546 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 01:14:20,546 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 01:14:20,596 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 01:14:20,844 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:03,044 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:10:12,730 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:10:12,731 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:10:12,731 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:10:12,731 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:10:12,731 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:10:12,731 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:10:12,736 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:10:12,736 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:10:13,068 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:10:13,068 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:10:13,069 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:10:13,070 - __main__ - INFO - Training stacked model...
2024-12-08 10:10:13,096 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,110 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,116 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,123 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,132 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,141 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,154 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,167 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,176 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,190 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,208 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,234 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,264 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,592 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:10:13,594 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:13,594 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:10:13,597 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:10:16,144 - __main__ - INFO - Model Performance:
2024-12-08 10:10:16,144 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:10:16,144 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:10:16,144 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:10:16,144 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:10:16,145 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:10:16,146 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:10:16,146 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:10:16,240 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:10:16,532 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:38,661 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:11:45,816 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:11:45,817 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:11:45,817 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:11:45,817 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:11:45,817 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:11:45,817 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:11:45,823 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:11:45,823 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:11:46,268 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:11:46,268 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:11:46,268 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:11:46,271 - __main__ - INFO - Training stacked model...
2024-12-08 10:11:46,298 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,307 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,311 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,315 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,320 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,324 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,329 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,335 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,341 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,347 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,360 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,367 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,380 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,593 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:11:46,594 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:46,594 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:11:46,597 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:11:51,825 - __main__ - INFO - Model Performance:
2024-12-08 10:11:51,825 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:11:51,825 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:11:51,825 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:11:51,825 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:11:51,826 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:11:51,827 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:11:51,827 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:11:51,943 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:11:52,193 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:35,160 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:12:42,138 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:12:42,138 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:12:42,138 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:12:42,138 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:12:42,138 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:12:42,139 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:12:42,143 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:12:42,143 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:12:42,430 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:12:42,430 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:12:42,430 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:12:42,432 - __main__ - INFO - Training stacked model...
2024-12-08 10:12:42,459 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,467 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,472 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,476 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,482 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,487 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,492 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,497 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,503 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,509 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,516 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,535 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,556 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,987 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:12:42,988 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:42,988 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:12:42,991 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:12:45,288 - __main__ - INFO - Model Performance:
2024-12-08 10:12:45,288 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:12:45,288 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:12:45,288 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:12:45,288 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:12:45,289 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:12:45,290 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:12:45,290 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:12:45,391 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:12:45,640 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:35,911 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:42:37,184 - __main__ - ERROR - Error in model training: 'Builder' object has no attribute 'stop'
2024-12-08 10:42:37,185 - __main__ - ERROR - Error in main: 'Builder' object has no attribute 'stop'
2024-12-08 10:42:47,175 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:42:57,920 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:42:57,920 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:42:57,920 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:42:57,920 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:42:57,920 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:42:57,922 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:42:57,933 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:42:57,933 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:42:58,104 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:42:58,105 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:42:58,105 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:42:58,108 - __main__ - INFO - Training stacked model...
2024-12-08 10:42:58,142 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,154 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,160 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,167 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,173 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,178 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,185 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,190 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,196 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,204 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,225 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,232 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,249 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,828 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:42:58,830 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:42:58,830 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:42:58,833 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:01,241 - __main__ - INFO - Model Performance:
2024-12-08 10:43:01,241 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:43:01,241 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:43:01,242 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:43:01,242 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:43:01,243 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:43:01,244 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:43:01,245 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:43:01,371 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:43:01,717 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:13,478 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:43:20,567 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:43:20,567 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:43:20,567 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:43:20,567 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:43:20,567 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:43:20,568 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:43:20,572 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:43:20,572 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:43:20,896 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:43:20,896 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:43:20,896 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:43:20,900 - __main__ - INFO - Training stacked model...
2024-12-08 10:43:20,939 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,949 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,953 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,958 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,963 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,968 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,974 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,980 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,987 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:20,994 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:21,003 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:21,018 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:21,039 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:21,410 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:43:21,411 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:21,411 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:43:21,413 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:43:23,682 - __main__ - INFO - Model Performance:
2024-12-08 10:43:23,682 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:43:23,682 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:43:23,682 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:43:23,682 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:43:23,683 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:43:23,684 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:43:23,684 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:43:23,785 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:43:24,045 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:26,316 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:48:33,395 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:48:33,395 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:48:33,395 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:48:33,395 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:48:33,395 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:48:33,396 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:48:33,400 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:48:33,400 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:48:33,730 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:48:33,730 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:48:33,730 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:48:33,732 - __main__ - INFO - Training stacked model...
2024-12-08 10:48:33,760 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,771 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,774 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,778 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,783 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,787 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,792 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,797 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,803 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,808 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,814 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,829 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:33,839 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:34,241 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:48:34,243 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:34,243 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:48:34,245 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:48:36,414 - __main__ - INFO - Model Performance:
2024-12-08 10:48:36,414 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:48:36,415 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:48:36,415 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:48:36,415 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:48:36,415 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:48:36,416 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:48:36,416 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:48:36,507 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:48:36,770 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:32,601 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:53:39,848 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:53:39,848 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:53:39,848 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:53:39,849 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:53:39,849 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:53:39,849 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:53:39,853 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:53:39,853 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:53:40,054 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:53:40,054 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:53:40,054 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:53:40,056 - __main__ - INFO - Training stacked model...
2024-12-08 10:53:40,083 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,093 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,096 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,101 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,105 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,112 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,115 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,120 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,124 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,130 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,148 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,150 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,169 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,528 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:53:40,530 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:40,530 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:53:40,531 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:53:42,835 - __main__ - INFO - Model Performance:
2024-12-08 10:53:42,835 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:53:42,835 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:53:42,835 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:53:42,835 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:53:42,837 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:53:42,838 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:53:42,838 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:53:42,931 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:53:43,201 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:10,895 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 10:54:17,942 - __main__ - INFO - Successfully loaded tables:
2024-12-08 10:54:17,942 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 10:54:17,942 - __main__ - INFO - Discount: (25, 7)
2024-12-08 10:54:17,942 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 10:54:17,943 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 10:54:17,943 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 10:54:17,947 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 10:54:17,947 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 10:54:18,306 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 10:54:18,306 - __main__ - INFO - Number of numeric features: 23
2024-12-08 10:54:18,306 - __main__ - INFO - Number of categorical features: 3
2024-12-08 10:54:18,308 - __main__ - INFO - Training stacked model...
2024-12-08 10:54:18,334 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,342 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,345 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,348 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,353 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,358 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,362 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,368 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,373 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,378 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,390 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,397 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,407 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,820 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 10:54:18,821 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:18,822 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 10:54:18,823 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 10:54:23,816 - __main__ - INFO - Model Performance:
2024-12-08 10:54:23,816 - __main__ - INFO - R² score: 0.9832
2024-12-08 10:54:23,816 - __main__ - INFO - MSE: 5020.8544
2024-12-08 10:54:23,816 - __main__ - INFO - RMSE: 70.8580
2024-12-08 10:54:23,816 - __main__ - INFO - MAE: 60.7211
2024-12-08 10:54:23,817 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 10:54:23,818 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 10:54:23,818 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 10:54:23,919 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 10:54:24,190 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:40,152 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 20:32:50,894 - __main__ - INFO - Successfully loaded tables:
2024-12-08 20:32:50,895 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 20:32:50,895 - __main__ - INFO - Discount: (25, 7)
2024-12-08 20:32:50,895 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 20:32:50,895 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 20:32:50,895 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 20:32:50,910 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 20:32:50,910 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 20:32:51,177 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 20:32:51,178 - __main__ - INFO - Number of numeric features: 23
2024-12-08 20:32:51,178 - __main__ - INFO - Number of categorical features: 3
2024-12-08 20:32:51,181 - __main__ - INFO - Training stacked model...
2024-12-08 20:32:51,214 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,226 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,232 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,237 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,244 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,250 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,256 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,261 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,268 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,274 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,291 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,326 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:51,331 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:52,009 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 20:32:52,010 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:52,011 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 20:32:52,014 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 20:32:54,455 - __main__ - INFO - Model Performance:
2024-12-08 20:32:54,455 - __main__ - INFO - R² score: 0.9832
2024-12-08 20:32:54,455 - __main__ - INFO - MSE: 5020.8544
2024-12-08 20:32:54,455 - __main__ - INFO - RMSE: 70.8580
2024-12-08 20:32:54,455 - __main__ - INFO - MAE: 60.7211
2024-12-08 20:32:54,456 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 20:32:54,457 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 20:32:54,457 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 20:32:54,564 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 20:32:54,931 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:49,432 - __main__ - INFO - Starting enhanced model training process...
2024-12-08 21:11:57,025 - __main__ - INFO - Successfully loaded tables:
2024-12-08 21:11:57,025 - __main__ - INFO - Revenue: (25, 6)
2024-12-08 21:11:57,025 - __main__ - INFO - Discount: (25, 7)
2024-12-08 21:11:57,025 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-08 21:11:57,025 - __main__ - INFO - Reviews: (25, 7)
2024-12-08 21:11:57,027 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-08 21:11:57,037 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-08 21:11:57,037 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-08 21:11:57,355 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-08 21:11:57,355 - __main__ - INFO - Number of numeric features: 23
2024-12-08 21:11:57,355 - __main__ - INFO - Number of categorical features: 3
2024-12-08 21:11:57,358 - __main__ - INFO - Training stacked model...
2024-12-08 21:11:57,391 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,401 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,404 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,408 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,414 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,419 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,427 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,434 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,441 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,447 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,468 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,485 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,492 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,763 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-08 21:11:57,770 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:11:57,770 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-08 21:11:57,775 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-08 21:12:00,372 - __main__ - INFO - Model Performance:
2024-12-08 21:12:00,372 - __main__ - INFO - R² score: 0.9832
2024-12-08 21:12:00,372 - __main__ - INFO - MSE: 5020.8544
2024-12-08 21:12:00,372 - __main__ - INFO - RMSE: 70.8580
2024-12-08 21:12:00,372 - __main__ - INFO - MAE: 60.7211
2024-12-08 21:12:00,373 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-08 21:12:00,374 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-08 21:12:00,374 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-08 21:12:00,484 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-08 21:12:00,730 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:49,822 - __main__ - INFO - Starting enhanced model training process...
2024-12-09 09:10:59,294 - __main__ - INFO - Successfully loaded tables:
2024-12-09 09:10:59,294 - __main__ - INFO - Revenue: (25, 6)
2024-12-09 09:10:59,294 - __main__ - INFO - Discount: (25, 7)
2024-12-09 09:10:59,294 - __main__ - INFO - Price Correlation: (25, 6)
2024-12-09 09:10:59,294 - __main__ - INFO - Reviews: (25, 7)
2024-12-09 09:10:59,296 - __main__ - INFO - Found categories: ['ART AND CRAFTING MATERIALS', 'BATH AND BODY', 'BEDSHEETS', 'BICYCLES', 'BLANKETS', 'BOOKS', 'CANDLES', 'CLOTHING', 'COATS AND JACKETS', 'COOKWARE', 'DRINKWARE', 'ELECTRONICS', 'HOME & KITCHEN', 'MAKEUP', 'MOBILE PHONE ACCESSORIES', 'MOTOR VEHICLE PARTS', 'NAIL CARE', 'PERFUME AND COLOGNE', 'POSTERS AND ARTWORK', 'SKIN CARE', 'SOCKS', 'TOYS & GAMES', 'UNDERWEAR', 'VITAMINS AND SUPPLEMENTS', 'WINE']
2024-12-09 09:10:59,306 - __main__ - INFO - Final merged dataset shape: (25, 23)
2024-12-09 09:10:59,306 - __main__ - INFO - Available columns: ['Category', 'TotalRevenue', 'TotalSales', 'AveragePrice', 'ProductCount', 'AvgDiscountPercentage', 'AvgDiscountPercentage_disc', 'TotalDiscountedRevenue', 'PotentialRevenue', 'AvgSales', 'RevenueLossFromDiscount', 'DiscountROI', 'PriceRatingCorrelation', 'AvgPrice', 'AvgRating', 'AvgReviews', 'PriceRatingRelationship', 'TotalReviews', 'TotalSales_review', 'AvgRating_review', 'HighRatingCount', 'ReviewToSalesRatio', 'CustomerEngagementLevel']
2024-12-09 09:10:59,517 - __main__ - INFO - Created advanced features. Shape: (25, 44)
2024-12-09 09:10:59,517 - __main__ - INFO - Number of numeric features: 23
2024-12-09 09:10:59,517 - __main__ - INFO - Number of categorical features: 3
2024-12-09 09:10:59,519 - __main__ - INFO - Training stacked model...
2024-12-09 09:10:59,554 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,575 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,584 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,594 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,601 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,609 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,616 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,625 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,635 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,645 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,664 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,671 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:10:59,694 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:11:00,480 - py4j.clientserver - INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-09 09:11:00,481 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:11:00,482 - root - INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aveee/data-lakehouse-fp-big-data/venv/lib/python3.11/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
2024-12-09 09:11:00,484 - py4j.clientserver - INFO - Closing down clientserver connection
2024-12-09 09:11:02,486 - __main__ - INFO - Model Performance:
2024-12-09 09:11:02,486 - __main__ - INFO - R² score: 0.9832
2024-12-09 09:11:02,486 - __main__ - INFO - MSE: 5020.8544
2024-12-09 09:11:02,486 - __main__ - INFO - RMSE: 70.8580
2024-12-09 09:11:02,487 - __main__ - INFO - MAE: 60.7211
2024-12-09 09:11:02,487 - __main__ - WARNING - Feature importance length mismatch: 3 vs 53
2024-12-09 09:11:02,488 - __main__ - INFO - 
Top 10 Most Important Features:
2024-12-09 09:11:02,488 - __main__ - INFO -                  feature  importance  importance_percentage
1  AvgDiscountPercentage    0.541399              54.139880
0           AveragePrice    0.408668              40.866799
2              AvgRating    0.049933               4.993321
2024-12-09 09:11:02,578 - __main__ - INFO - Model saved to /home/aveee/data-lakehouse-fp-big-data/src/models/training/trained_models/sales_predictor.joblib
2024-12-09 09:11:02,800 - py4j.clientserver - INFO - Closing down clientserver connection
